### ISSUE TITLE
Full example

### ISSUE THREAD

**Issue by cwittlinger** [pantsbuild/example-django#1]
Is there an ETA when this Example is done?

**Comment by benjyw** [comment]
I'm working on it as we speak! Sorry for the delay, this was on the back burner for a while, but now it definitely needs to be done before my related workshop at DjangoCon EU in early June, and ideally long before that...

**Comment by cwittlinger** [comment]
Thanks for the quick reply. I am almost done with setting up a Django monorepo, however I have issues running it because some paths are not detected correctly after creating those PEX files. 

Really looking forward to the example ☺️

**Comment by benjyw** [comment]
Example is ready! If you still have issues feel free to ping us on [Slack](https://www.pantsbuild.org/docs/getting-help), or open another GitHub issue!
