### ISSUE TITLE
Migrate is not creating any tables

### ISSUE THREAD

**Issue by bastianwegge** [pantsbuild/example-django#17]
Haven't figured out why exactly but `./pants run helloworld/service/admin/manage.py -- migrate --database=users --database=greetings` is not creating any django-related tables for me, making the example not usable.

Migrations are running and obviously applying, but no django related tables are getting created.
```
❯ ./pants run helloworld/service/admin/manage.py -- migrate --database=users --database=greetings

Operations to perform:
  Apply all migrations: admin, auth, contenttypes, greet, person, sessions, translate
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying greet.0001_initial... OK
  Applying greet.0002_data... OK
  Applying person.0001_initial... OK
  Applying person.0002_data... OK
  Applying sessions.0001_initial... OK
  Applying translate.0001_initial... OK
  Applying translate.0002_data... OK
```

Here's the resulting `users.sqlite3` inspected using DataGrip:
<img width="293" alt="users" src="https://user-images.githubusercontent.com/1541474/158020383-e4427e14-4b0c-488d-b855-22d8005eb49a.png">

Here's the resulting `greetings.sqlite3` inspected using DataGrip:
<img width="258" alt="greetings" src="https://user-images.githubusercontent.com/1541474/158020377-02cb7247-7c8c-4f77-879b-12ef422c4dd4.png">

As you can see, `greet_greetings` is created as well as `translate_translations` but the other django related tables are not being created.

**Comment by benjyw** [comment]
Hmm, when I run `./pants run helloworld/service/admin/manage.py -- migrate --database=users --database=greetings` I don't get a users.sqlite3 file at all. But if I run just `./pants run helloworld/service/admin/manage.py -- migrate --database=users` I do, and it contains the Django `auth_*` and `django_*` tables, as well as the app's `person_person`. 

Can you try running migrate separately for each of the two databases? Multiple db support in Django is fragile, particularly around migrations.

**Comment by bastianwegge** [comment]
I feel a bit tricked by my computer, when I ran `./pants run helloworld/service/admin/manage.py -- migrate --database=users` before it prompted me with:

```
...
django.db.utils.OperationalError: no such table: django_content_type
```

Now it seems to work. Maybe that's something you can point out in the readme, to do both separately. I remember from your youtube-workshop that you even said doing it separately, that's why I tried. Thanks for pointing that out again.

**Comment by benjyw** [comment]
Glad it works now, and thanks for the doc update!
